version: '3'

services:
    app:
        image: bitnami/laravel:10
        ports:
            - 8000:8000
        environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_DATABASE='track-your-pack'
        - DB_USERNAME=root
        - DB_PASSWORD='track-your-pack'
        volumes:
            - ./app:/app
        stdin_open: true
        tty: true
    db:
        image: mysql:8.2.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'track-your-pack'
        volumes:
            - ./db_data:/var/lib/mysql
        stdin_open: true
        tty: true
    user-view:
        image: next-js:14
        ports:
            - 3000:3000
        volumes:
            - ./user-view:/app
            - /app/node_modules
            - /app/.next
        stdin_open: true
        tty: true