import { Inter } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.min.css"; 
import './globals.css'
import NavBar from './components/NavBar'
import RoleContext from './context/RoleContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
title: 'Create Next App',
description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    return (
        <html lang="en">
        <body className={inter.className}>
            <RoleContext>
                {children}
                <NavBar />
            </RoleContext>
        </body>
        </html>
    )
}
